sudo: required
services:
  - docker

script:
  - docker-compose -f docker-compose.travis.yml build
  - docker-compose -f docker-compose.travis.yml run --rm -e $GITHUB_API_TOKEN -e $MAGE_ACCOUNT_PUBLIC_KEY -e $MAGE_ACCOUNT_PRIVATE_KEY magento2 magento
